Implements ability to disable scroll to top
enszrlu/NextStep pull request #15
Opened 2024-12-20 05:02 UTC by 0ctan33

Issue #10 
Adds optional parameter scrollToTop to control auto scroll behaviour on completion. 

Example: 
<NextStep scrollToTop={false} {...otherProps}>

2024-12-22 10:41 UTC, enszrlu requested changes
Thanks for doing it, it was long lasting issue to be fixed. 

@0ctan33 works when tour finishes but breaks when step does not have a selector. same useEffect was used for scrolling to top when step without selector used as tooltip appears on top middle of the app. See demo website step 12 and 1 for example. If scrolltotop false, this does not work. 

We can separate the useEffect for isNextStepVisible only and use this logic there. 

Also can you please rebase to  https://github.com/enszrlu/NextStep/tree/241219-support-other-react-libraries so we can roll this out on beta version?

2024-12-22 14:43 UTC, 0ctan33 commented
@enszrlu ah I see. I've fixed it up locally, will do some more testing and PR again this week

2025-01-03 09:14 UTC, enszrlu commented
> @enszrlu ah I see. I've fixed it up locally, will do some more testing and PR again this week

Hi, if you can push it. I am happy to test it 😊

2025-01-06 10:38 UTC, 0ctan33 commented
hey @enszrlu ! apologies for the delay, forgot how close it was to the new year. I'm back on the 16th if this can wait?
do you have LinkedIn?

2025-01-06 11:06 UTC, enszrlu commented
> hey @enszrlu ! apologies for the delay, forgot how close it was to the new year. I'm back on the 16th if this can wait?
> do you have LinkedIn?

No worries at all, it is not urgent. I was just checking all my todos. Happy new year BTW 😊

I just added LinkedIn to my profile.

2025-01-17 11:33 UTC, closed without merging